### ISSUE TITLE
Greedy Snack or Greedy Snake？ (逃

### ISSUE THREAD

**Issue by greatoyster** [MeliaLiu/pylash_sillyGame#1]

**Comment by MeliaLiu** [comment]
23333333 thx
I spell it wrongly again
By the way
Who are u😂

Sent from my iPhone

On Jul 23, 2020, at 5:18 PM, greatoyster <notifications@github.com> wrote:

﻿

**Comment by MeliaLiu** [comment]
Cautiousoyster 🥇 :)

**Comment by MeliaLiu** [comment]
Hhh
